### ISSUE TITLE
There is no need to have in internal API updateMenuItem and patchMenuItems

### ISSUE THREAD

**Issue by milanhorvath** [onecx/onecx-workspace#4]
onecx-workspace-svc: MenuInternalRestController (MenuInternalApi)
updateMenuItem and patchMenuItems do the same just the first do it for one item the second for a list of items
So probably there can be just the patch and update can send a list of one item

**Comment by andrejpetras** [comment]
Fix by https://github.com/onecx/onecx-workspace-svc/pull/30
